spring:
  application:
    name: hotel-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: hotel
    password: hotel
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8087/realms/hotel_app
          jwk-set-uri: http://localhost:8087/realms/hotel_app/protocol/openid-connect/certs

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
